"""Code analysis module for ArkTS review units and retrieval features."""

from arkts_code_reviewer.code_analysis.analyzer import CodeAnalyzer
from arkts_code_reviewer.code_analysis.arkts_tree_sitter_parser import ArktsTreeSitterParser
from arkts_code_reviewer.code_analysis.change_review import (
    CHANGE_REVIEW_BUILD_SCHEMA_VERSION,
    ChangeSetReviewUnitBuilder,
    build_change_review_units,
)
from arkts_code_reviewer.code_analysis.change_set import (
    CHANGE_SET_SCHEMA_VERSION,
    DIFF_NORMALIZER_VERSION,
    ChangeAtom,
    ChangeAtomInput,
    ChangedFile,
    ChangedFileInput,
    ChangeSet,
    ChangeSetDiagnostic,
    CodeSourceSnapshot,
    DiffPosition,
    normalize_change_set,
)
from arkts_code_reviewer.code_analysis.file_analysis_models import (
    FILE_ANALYSIS_SCHEMA_VERSION,
    CodeSourceRef,
    DeclarationOccurrence,
    ExactRange,
    FactKind,
    FactOccurrence,
    FileAnalysis,
    FileParseResult,
    FileParserQuality,
    OwnerRef,
    ReviewRegion,
    ScopedFacts,
    UnitFactScope,
)
from arkts_code_reviewer.code_analysis.file_analysis_parser import (
    ArktsFileAnalysisParser,
    FileAnalysisParser,
    LegacyFileAnalysisAdapter,
)
from arkts_code_reviewer.code_analysis.lexical import LexicalParser
from arkts_code_reviewer.code_analysis.models import (
    REVIEW_UNIT_BUILD_SCHEMA_VERSION,
    AnalysisResult,
    CodeFacts,
    CodeFeatures,
    Declaration,
    FileHunk,
    FileInput,
    ParserQuality,
    ReviewUnit,
    ReviewUnitBuildResult,
    ReviewUnitDiagnostic,
    ReviewUnitFileResult,
    ReviewUnitSpan,
)
from arkts_code_reviewer.code_analysis.tree_sitter_parser import TreeSitterParser

__all__ = [
    "AnalysisResult",
    "ArktsFileAnalysisParser",
    "ArktsTreeSitterParser",
    "CHANGE_REVIEW_BUILD_SCHEMA_VERSION",
    "CHANGE_SET_SCHEMA_VERSION",
    "ChangeAtom",
    "ChangeAtomInput",
    "ChangedFile",
    "ChangedFileInput",
    "ChangeSet",
    "ChangeSetDiagnostic",
    "ChangeSetReviewUnitBuilder",
    "CodeSourceRef",
    "CodeSourceSnapshot",
    "CodeAnalyzer",
    "CodeFacts",
    "CodeFeatures",
    "Declaration",
    "DeclarationOccurrence",
    "DIFF_NORMALIZER_VERSION",
    "DiffPosition",
    "ExactRange",
    "FactKind",
    "FactOccurrence",
    "FILE_ANALYSIS_SCHEMA_VERSION",
    "FileAnalysis",
    "FileInput",
    "FileHunk",
    "FileAnalysisParser",
    "FileParseResult",
    "FileParserQuality",
    "LegacyFileAnalysisAdapter",
    "LexicalParser",
    "ParserQuality",
    "OwnerRef",
    "REVIEW_UNIT_BUILD_SCHEMA_VERSION",
    "ReviewUnit",
    "ReviewUnitBuildResult",
    "ReviewUnitDiagnostic",
    "ReviewUnitFileResult",
    "ReviewRegion",
    "ReviewUnitSpan",
    "ScopedFacts",
    "TreeSitterParser",
    "UnitFactScope",
    "build_change_review_units",
    "normalize_change_set",
]
