DEFAULT_ARKUI_COMPONENTS: frozenset[str] = frozenset(
    {
        "AlphabetIndexer",
        "Blank",
        "Button",
        "Canvas",
        "Checkbox",
        "CheckboxGroup",
        "Column",
        "ColumnSplit",
        "Counter",
        "DataPanel",
        "DatePicker",
        "Divider",
        "Flex",
        "FlowItem",
        "ForEach",
        "FormLink",
        "Gauge",
        "Grid",
        "GridCol",
        "GridItem",
        "GridRow",
        "Hyperlink",
        "Image",
        "ImageAnimator",
        "ImageSpan",
        "LazyForEach",
        "Line",
        "List",
        "ListItem",
        "ListItemGroup",
        "LoadingProgress",
        "Marquee",
        "Menu",
        "MenuItem",
        "NavDestination",
        "Navigation",
        "Navigator",
        "Panel",
        "Path",
        "PatternLock",
        "PluginComponent",
        "Polygon",
        "Polyline",
        "Progress",
        "QRCode",
        "Radio",
        "Rating",
        "Refresh",
        "RelativeContainer",
        "Repeat",
        "RichEditor",
        "RichText",
        "Row",
        "RowSplit",
        "Scroll",
        "Search",
        "Select",
        "Shape",
        "SideBarContainer",
        "Slider",
        "Span",
        "Stack",
        "Stepper",
        "Swiper",
        "Tabs",
        "Text",
        "TextArea",
        "TextClock",
        "TextInput",
        "TextPicker",
        "TextTimer",
        "Toggle",
        "Video",
        "WaterFlow",
        "Web",
        "XComponent",
    }
)

ARKUI_ATTRIBUTES: frozenset[str] = frozenset(
    {
        "accessibilityDescription",
        "accessibilityGroup",
        "accessibilityLevel",
        "accessibilityText",
        "align",
        "alignItems",
        "animation",
        "aspectRatio",
        "backgroundColor",
        "border",
        "borderRadius",
        "fontColor",
        "fontSize",
        "fontWeight",
        "height",
        "layoutWeight",
        "margin",
        "objectFit",
        "onAppear",
        "onBlur",
        "onChange",
        "onClick",
        "onComplete",
        "onDisAppear",
        "onError",
        "onFocus",
        "onTouch",
        "padding",
        "placeholder",
        "position",
        "rotate",
        "transition",
        "visibility",
        "width",
    }
)

STATE_DECORATORS: frozenset[str] = frozenset(
    {
        "@BuilderParam",
        "@Consume",
        "@Local",
        "@Link",
        "@ObjectLink",
        "@Observed",
        "@ObservedV2",
        "@Once",
        "@Param",
        "@Prop",
        "@Provide",
        "@Require",
        "@State",
        "@StorageLink",
        "@StorageProp",
        "@Trace",
        "@Watch",
    }
)

LIFECYCLE_SYMBOLS: frozenset[str] = frozenset(
    {
        "aboutToAppear",
        "aboutToDisappear",
        "onBackPress",
        "onPageHide",
        "onPageShow",
        "onReady",
    }
)

GLOBAL_APIS: frozenset[str] = frozenset(
    {
        "$r",
        "$rawfile",
        "AppStorage.get",
        "AppStorage.setOrCreate",
        "animateTo",
        "clearInterval",
        "clearTimeout",
        "setInterval",
        "setTimeout",
    }
)

OHOS_MODULE_PREFIXES: dict[str, str] = {
    "@ohos.abilityAccessCtrl": "abilityAccessCtrl",
    "@ohos.app.ability.common": "common",
    "@ohos.data.preferences": "preferences",
    "@ohos.data.relationalStore": "relationalStore",
    "@ohos.emitter": "emitter",
    "@ohos.file.fileuri": "fileUri",
    "@ohos.file.fs": "fs",
    "@ohos.hilog": "hilog",
    "@ohos.media": "media",
    "@ohos.multimedia.audio": "audio",
    "@ohos.multimedia.camera": "camera",
    "@ohos.multimedia.image": "image",
    "@ohos.multimedia.media": "media",
    "@ohos.net.http": "http",
    "@ohos.net.socket": "socket",
    "@ohos.promptAction": "promptAction",
    "@ohos.resourceschedule.workScheduler": "workScheduler",
    "@ohos.router": "router",
    "@ohos.sensor": "sensor",
    "@ohos.systemTimer": "systemTimer",
    "@ohos.taskpool": "taskpool",
    "@ohos.worker": "worker",
    "@system.router": "router",
}

SDK_MODULE_PREFIXES: tuple[str, ...] = ("@ohos.", "@kit.", "@system.")

IMAGE_COMPONENTS: frozenset[str] = frozenset({"Image", "ImageSpan", "ImageAnimator"})
LAYOUT_COMPONENTS: frozenset[str] = frozenset(
    {"Column", "Row", "Flex", "Grid", "GridRow", "GridCol", "Stack", "RelativeContainer"}
)
INTERACTIVE_COMPONENTS: frozenset[str] = frozenset(
    {"Button", "Toggle", "Slider", "TextInput", "TextArea", "Search", "Checkbox", "Radio"}
)
